name: Deploy-Demo-App

on:
  push:
    branches: [ "main" ]
  

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Setup become password file
        run: |
          echo "${{ secrets.BECOME_PASS }}" > become-pass.txt
          chmod 600 become-pass.txt

      - name: Download Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env: 
           ANSIBLE_USER             : ${{ secrets.ANSIBLE_USER }}
           ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          ansible-playbook -vvv -i ansible/inventory/hosts --private-key private-key.pem -u user --extra-vars='ansible_become_pass=${{ secrets.BECOME_PASS }} ansible/app-demo.yml
          
